---
battery_critical_level: 8
battery_level_check_interval: 30 # in seconds

users:
  - artem
  - crypto

sudo_users: []
docker_users:
  - artem
qemu_users:
  - artem

# System
## swap
cryptswap_name: swap
swap_mapper_device: "/dev/disk/by-label/{{ cryptswap_name }}"
## hibernate
crypthibernate_name: hibernate
hibernate_mapper_device: "/dev/disk/by-label/{{ crypthibernate_name }}"

# NOTE: please monitor and keep it up to date with latest version available
# through LLVM official repository - https://apt.llvm.org/, considering of
# course your own needs.
# You can install multiply LLVM versions
llvm_versions:
  - 22

jdk_versions:
  - 21

# AWS CLI
sam_cli_zip_url: https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip

# LunarG Vulkan SDK
vulkan_sdk_version: 1.4.304.1
vulkan_sdk_install_dir: /opt/vulkansdk

rpm_based_pkg_managers: [dnf, dnf5, yum, zypper]
deb_based_pkg_managers: [apt]

# Docker
nvidia_container_toolkit: true
nvidia_kubernetes_device_plugin_version: v0.17.1

# Kubernetes
kube_kind_version: v0.27.0
kube_kustomize_version: v5.6.0
kube_helm_version: v3.17.3
kube_install_kubeflow: true
kube_kind: false
kube_microk8s: true
kube_metallb_ip_range: 10.10.10.240-10.10.10.254

# Kubeflow
kubeflow_version: v1.10.0
kubeflow_on_kind: false
kubeflow_on_microk8s: true

# Parameters required by Kubeflow components (extend as needed)
sysctl_parameters:
  fs.inotify.max_user_instances: 1280
  fs.inotify.max_user_watches: 655360
  net.ipv4.ip_forward: "1"
  net.bridge.bridge-nf-call-iptables: "1"
  net.netfilter.nf_conntrack_max: "131072"


kernel_modules:
  - br_netfilter
  - vxlan
  - nf_conntrack

# Override this to install a different Watchman release
watchman_version: 2025.07.28.00
