---
battery_critical_level: 8
battery_level_check_interval: 30 # in seconds

users:
  - artem
  - crypto

sudo_users: []
docker_users:
  - artem
qemu_users:
  - artem

# System
## swap
cryptswap_name: swap
swap_mapper_device: "/dev/disk/by-label/{{ cryptswap_name }}"
## hibernate
crypthibernate_name: hibernate
hibernate_mapper_device: "/dev/disk/by-label/{{ crypthibernate_name }}"

# NOTE: please monitor and keep it up to date with latest version available
# through LLVM official repository - https://apt.llvm.org/, considering of
# course your own needs.
# You can install multiply LLVM versions
llvm_versions:
  - 21

jdk_versions:
  - 21

# AWS CLI
sam_cli_zip_url: https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip

# LunarG Vulkan SDK
vulkan_sdk_version: 1.4.304.1
vulkan_sdk_install_dir: /opt/vulkansdk

rpm_based_pkg_managers: [dnf, dnf5, yum, zypper]
deb_based_pkg_managers: [apt]

# Docker
nvidia_container_toolkit: true
nvidia_kubernetes_device_plugin_version: v0.17.1

# Kubernetes
kube_kind_version: v0.27.0
kube_kustomize_version: v5.6.0
kube_install_kubeflow: true
kube_kind: true
kube_microk8s: false
kubeflow_version: v1.10.0
kubeflow_on_kind: true
kubeflow_on_microk8s: false
metallb_ip_range: 192.168.1.240-192.168.1.250
