---
- name: Ensure Snap is installed (Ubuntu-specific)
  ansible.builtin.apt:
    name: snapd
    state: present
  tags: [docker]

- name: Install MicroK8s via snap (Ubuntu-specific)
  community.general.snap:
    name: microk8s
    classic: true
    state: present
  tags: [docker]

- name: Add current user to MicroK8s group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  loop: "{{ docker_users }}"
  tags: [docker]

- name: Ensure microk8s is running
  ansible.builtin.command: microk8s start
  register: microk8s_start_status
  changed_when: true
  failed_when: microk8s_start_status.rc != 0
  tags: [docker]

- name: Wait for MicroK8s to be ready
  ansible.builtin.command: microk8s status --wait-ready
  register: microk8s_status
  changed_when: false
  failed_when: microk8s_status.rc != 0
  tags: [docker]

- name: Enable DNS
  ansible.builtin.command: microk8s enable dns
  changed_when: true
  tags: [docker]

- name: Enable Storage
  ansible.builtin.command: microk8s enable storage
  changed_when: true
  tags: [docker]

- name: Enable Dashboard
  ansible.builtin.command: microk8s enable dashboard
  changed_when: true
  tags: [docker]

- name: Enable Ingress
  ansible.builtin.command: microk8s enable ingress
  changed_when: true
  tags: [docker]

- name: Enable MetalLB with IP range
  ansible.builtin.command: microk8s enable metallb:{{ metallb_ip_range }}
  changed_when: true
  tags: [docker]

# Example of using Ansible template to place a demo YAML
- name: Deploy sample workload
  ansible.builtin.template:
    src: sample-deployment.yaml.j2
    dest: /tmp/sample-deployment.yaml
    mode: "0644"
  tags: [docker]

- name: Apply the sample deployment
  ansible.builtin.command: microk8s kubectl apply -f /tmp/sample-deployment.yaml
  changed_when: true
  tags: [docker]

- name: Install Kubeflow
  ansible.builtin.include_tasks: kubeflow_microk8s.yml
  when:
    - kube_install_kubeflow | default(false)
    - kubeflow_on_microk8s | default(false)
  tags: [docker]

- name: Stop microk8s to save resources
  ansible.builtin.command: microk8s stop
  changed_when: true
  tags: [docker]
