---
- name: Ensure Snap is installed (Ubuntu-specific)
  ansible.builtin.apt:
    name: snapd
    state: present
  tags: [docker]

- name: Install MicroK8s via snap (Ubuntu-specific)
  community.general.snap:
    name: microk8s
    classic: true
    # channel: 1.32.2/stable # or any channel you prefer (e.g., latest)
    state: present
  tags: [docker]

- name: Add current user to MicroK8s group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  loop: "{{ docker_users }}"
  tags: [docker]

- name: Wait for MicroK8s to be ready
  ansible.builtin.command: microk8s status --wait-ready
  register: microk8s_status
  changed_when: false
  failed_when: microk8s_status.rc != 0
  tags: [docker]

- name: Enable common add-ons (DNS, dashboard, storage) - optional
  ansible.builtin.command: microk8s enable dns storage dashboard
  changed_when: true
  tags: [docker]
  # The above can also be done with `command`, but `shell` is used
  # to pass multiple arguments in one shot.

# Example of using Ansible template to place a demo YAML
- name: Deploy sample workload
  ansible.builtin.template:
    src: sample-deployment.yaml.j2
    dest: /tmp/sample-deployment.yaml
    mode: "0644"
  tags: [docker]

- name: Apply the sample deployment
  ansible.builtin.command: microk8s kubectl apply -f /tmp/sample-deployment.yaml
  changed_when: true
  tags: [docker]
