---
- name: Install Single Node Kubernetes (MicroK8s)
  ansible.builtin.include_tasks: microk8s/main.yml
  when:
    - ansible_facts['distribution'] in ["Pop!_OS", "Ubuntu"]
    - kube_microk8s | default(false)
  tags: [kubernetes]

- name: Inform about unsupported OS
  ansible.builtin.debug:
    msg: "Microk8s Kubernetes role does not support this OS: {{ ansible_facts['distribution'] }}. It supports only Ubuntu based distros"
  when:
    - ansible_facts['distribution'] not in ["Pop!_OS", "Ubuntu"]
    - kube_microk8s | default(false)
  tags: [kubernetes]

- name: Install Single Node Kubernetes (Kind)
  ansible.builtin.include_tasks: kind/main.yml
  when: kube_kind | default(false)
  tags: [kubernetes]
