---
- name: Install Kubeflow
  ansible.builtin.include_tasks: microk8s_prereqs.yml
  tags: [kubernetes]

- name: Ensure Snap is installed (Ubuntu-specific)
  ansible.builtin.apt:
    name: snapd
    state: present
  tags: [kubernetes]

- name: Install MicroK8s via snap (Ubuntu-specific)
  community.general.snap:
    name: microk8s
    classic: true
    state: present
  tags: [kubernetes]

- name: Add users to MicroK8s group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  loop: "{{ docker_users }}"
  tags: [kubernetes]

- name: Ensure microk8s is running
  ansible.builtin.command: microk8s start
  register: microk8s_start_status
  changed_when: true
  failed_when: microk8s_start_status.rc != 0
  tags: [kubernetes]

- name: Wait for MicroK8s to be ready
  ansible.builtin.command: microk8s status --wait-ready
  register: microk8s_status
  changed_when: false
  failed_when: microk8s_status.rc != 0
  tags: [kubernetes]

- name: Enable DNS
  ansible.builtin.command: microk8s enable dns
  changed_when: true
  tags: [kubernetes]

- name: Enable Storage
  ansible.builtin.command: microk8s enable storage
  changed_when: true
  tags: [kubernetes]

- name: Enable Dashboard
  ansible.builtin.command: microk8s enable dashboard
  changed_when: true
  tags: [kubernetes]

- name: Enable Ingress
  ansible.builtin.command: microk8s enable ingress
  changed_when: true
  tags: [kubernetes]

- name: Check if MetalLB is already enabled
  ansible.builtin.command: microk8s status --format short
  register: microk8s_status
  changed_when: false
  tags: [kubernetes]

- name: Enable MetalLB
  ansible.builtin.command: "microk8s.enable metallb:{{ kube_metallb_ip_range }}"
  when: "'metallb: enabled' not in microk8s_status.stdout"
  become: true
  register: result
  changed_when: "'MetalLB is enabled' in result.stdout"
  tags: [kubernetes]

- name: Enable NVIDIA hardware (GPU and network) support in Microk8s
  ansible.builtin.command: microk8s.enable nvidia
  when: nvidia_container_toolkit | default(false)
  changed_when: true
  tags: [kubernetes]

- name: Stop microk8s to save resources
  ansible.builtin.command: microk8s stop
  changed_when: true
  tags: [kubernetes]
