---
- name: Install entr
  ansible.builtin.package:
    name: entr
    state: present
  tags:
    - file_monitoring_packages
    - entr

- name: Install watchman
  ansible.builtin.include_tasks: watchman.yml
  tags:
    - file_monitoring_packages
    - watchman
